/**
* Create historical table
*/
CREATE TABLE STOCK_HISTORICAL (
	HISTORICAL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	OPEN REAL,
	HIGH REAL,
	LOW REAL,
	CLOSE REAL,
	ADJ_CLOSE REAL,
	VOLUME INTEGER,
  STOCK_DT_MAP_ID INTEGER REFERENCES STOCK_DATE_MAP(STOCK_DT_MAP_ID)
);

/**
* Create historical table view
*/
CREATE VIEW STOCK_HISTORICAL_VIEW AS
SELECT SDM.STOCK_DATE STK_DATE, ST.SYMBOL STOCK, AVG(SH.CLOSE) AVG_PRICE FROM STOCK_HISTORICAL SH
INNER JOIN STOCK_DATE_MAP SDM ON SH.STOCK_DT_MAP_ID = SDM.STOCK_DT_MAP_ID
INNER JOIN STOCK_TICKER ST ON ST.TICKER_ID = SDM.TICKER_ID
GROUP BY SDM.STOCK_DATE, ST.SYMBOL;
